/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.geom.Line2D;

/**
 *
 * @author juann
 */
public class EJEMPLO extends javax.swing.JPanel {
        double num1;
        double num2;
        double resultado;
        String operacion;
    /**
     * Creates new form EJEMPLO
     */
    public EJEMPLO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPantalla = new javax.swing.JTextField();
        btndivision = new javax.swing.JButton();
        btncoma = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btniguales = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        btnsuma = new javax.swing.JButton();
        btnresta = new javax.swing.JButton();
        btnmultiplicar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPantalla.setBackground(new java.awt.Color(0, 255, 0));
        txtPantalla.setForeground(new java.awt.Color(255, 255, 255));
        txtPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPantallaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 6, 190, 50));

        btndivision.setBackground(new java.awt.Color(204, 204, 204));
        btndivision.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btndivision.setForeground(new java.awt.Color(255, 255, 255));
        btndivision.setText("%");
        jPanel1.add(btndivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 40, 40));

        btncoma.setBackground(new java.awt.Color(204, 204, 204));
        btncoma.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btncoma.setForeground(new java.awt.Color(255, 255, 255));
        btncoma.setText(",");
        jPanel1.add(btncoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 50, 50));

        btn0.setBackground(new java.awt.Color(204, 204, 204));
        btn0.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 50, 50));

        btniguales.setBackground(new java.awt.Color(204, 204, 204));
        btniguales.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btniguales.setForeground(new java.awt.Color(255, 255, 255));
        btniguales.setText("=");
        btniguales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnigualesActionPerformed(evt);
            }
        });
        jPanel1.add(btniguales, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 50, 50));

        btn1.setBackground(new java.awt.Color(204, 204, 204));
        btn1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 50, 50));

        btn2.setBackground(new java.awt.Color(204, 204, 204));
        btn2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 50, 50));

        btn3.setBackground(new java.awt.Color(204, 204, 204));
        btn3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 50, 50));

        btn4.setBackground(new java.awt.Color(204, 204, 204));
        btn4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, 50));

        btn5.setBackground(new java.awt.Color(204, 204, 204));
        btn5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 50, 50));

        btn6.setBackground(new java.awt.Color(204, 204, 204));
        btn6.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 50, 50));

        btn7.setBackground(new java.awt.Color(204, 204, 204));
        btn7.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 50));

        btn8.setBackground(new java.awt.Color(204, 204, 204));
        btn8.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 50, 50));

        btn9.setBackground(new java.awt.Color(204, 204, 204));
        btn9.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        jPanel1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 50, 50));

        btnborrar.setBackground(new java.awt.Color(204, 204, 204));
        btnborrar.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnborrar.setForeground(new java.awt.Color(255, 255, 255));
        btnborrar.setText("C");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 40, 40));

        btnsuma.setBackground(new java.awt.Color(204, 204, 204));
        btnsuma.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnsuma.setForeground(new java.awt.Color(255, 255, 255));
        btnsuma.setText("+");
        btnsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumaActionPerformed(evt);
            }
        });
        jPanel1.add(btnsuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 40, 40));

        btnresta.setBackground(new java.awt.Color(204, 204, 204));
        btnresta.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnresta.setForeground(new java.awt.Color(255, 255, 255));
        btnresta.setText("-");
        jPanel1.add(btnresta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 40, 40));

        btnmultiplicar.setBackground(new java.awt.Color(204, 204, 204));
        btnmultiplicar.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnmultiplicar.setForeground(new java.awt.Color(255, 255, 255));
        btnmultiplicar.setText("x");
        jPanel1.add(btnmultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
this.txtPantalla.setText(this.txtPantalla.getText()+ "7");
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7ActionPerformed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
       this.txtPantalla.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnborrarActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
 this.txtPantalla.setText(this.txtPantalla.getText()+"0");       
// TODO add your handling code here:
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnigualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnigualesActionPerformed
        
        num2 =Double.parseDouble(this.txtPantalla.getText());
        switch (operacion ) {
            case "+a":
               resultado =(num1+num2);
                break;
            default:
                throw new AssertionError();
        }
   
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnigualesActionPerformed

    private void btnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumaActionPerformed
this.txtPantalla.setText("+");
double num1 =Double.parseDouble(this.txtPantalla.getText());
 operacion ="+";
 this.txtPantalla.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsumaActionPerformed

    private void txtPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPantallaActionPerformed


    public static void main(String[] args) {
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btncoma;
    private javax.swing.JButton btndivision;
    private javax.swing.JButton btniguales;
    private javax.swing.JButton btnmultiplicar;
    private javax.swing.JButton btnresta;
    private javax.swing.JButton btnsuma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtPantalla;
    // End of variables declaration//GEN-END:variables
}
